"use client";
import {useEffect,useState} from "react";
const sources=["BBC World","Reuters World","Al Jazeera","CNN World","The Guardian World"];
const steps=["Fetch source","Understand story","Write Tamil","Create original graphic","Human approval","Publish to Instagram"];

export default function Home(){
 const [tab,setTab]=useState("Dashboard"); const [running,setRunning]=useState(false); const [result,setResult]=useState<any>(null); const [posts,setPosts]=useState<any[]>([]);
 const [secret,setSecret]=useState(""); const [imageBusy,setImageBusy]=useState<string|null>(null);
 useEffect(()=>{const s=sessionStorage.getItem("hijaz_admin_secret"); if(s)setSecret(s); loadPosts();},[]);
 async function loadPosts(){try{const r=await fetch("/api/posts"); const d=await r.json(); if(d.ok)setPosts(d.posts||[]);}catch{}}
 async function runTest(){setRunning(true);setResult(null);try{const h:Record<string,string>={}; const ingest=process.env.NEXT_PUBLIC_INGEST_SECRET; if(ingest)h.authorization="Bearer "+ingest; const r=await fetch("/api/ingest",{method:"POST",headers:h}); const d=await r.json(); setResult(d); await loadPosts();}catch(e){setResult({ok:false,error:e instanceof Error?e.message:"Request failed"});}finally{setRunning(false);}}
 function saveSecret(v:string){setSecret(v);sessionStorage.setItem("hijaz_admin_secret",v);}
 async function moderate(id:string,action:string){if(!secret)return alert("Enter your ADMIN_SECRET first."); const r=await fetch("/api/posts/"+id,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+secret},body:JSON.stringify({action})}); const d=await r.json(); if(!r.ok)return alert(d.error||"Action failed"); await loadPosts();}
 async function generate(post:any){if(!secret)return alert("Enter your ADMIN_SECRET first.");setImageBusy(post.id);try{const r=await fetch("/api/generate",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+secret},body:JSON.stringify({id:post.id,headline:post.editorial?.headline_tamil||post.title,source:post.source,category:post.editorial?.category||"World News"})});const d=await r.json();if(!r.ok)return alert(d.error||"Graphic generation failed");setPosts(x=>x.map(p=>p.id===post.id?{...p,imageUrl:d.url,status:"approved"}:p));}finally{setImageBusy(null);}}
 async function publish(post:any){if(!secret||!post.imageUrl)return alert("Approve and generate the graphic first."); const caption=post.editorial?.caption_tamil||post.editorial?.headline_tamil||post.title; const r=await fetch("/api/publish",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+secret},body:JSON.stringify({id:post.id,caption,imageUrl:post.imageUrl})});const d=await r.json();if(!r.ok)return alert(d.error||"Publish failed");await loadPosts();}
 const pending=posts.filter(p=>p.status==="pending_approval"||p.status==="approved"); const published=posts.filter(p=>p.status==="published");
 return <main className="app"><aside className="sidebar"><div className="logo"><div className="mark">HA</div><div><b>Hijaz Tamil News</b><span>@hijaz_ah</span></div></div>
 <nav>{["Dashboard","Pending Posts","Published","Sources","Settings"].map(x=><button className={tab===x?"selected":""} onClick={()=>setTab(x)} key={x}><span>{x==="Dashboard"?"⌂":x==="Pending Posts"?"◷":x==="Published"?"✓":x==="Sources"?"◉":"⚙"}</span>{x}</button>)}</nav>
 <div className="safe"><div><i/> Automation ready</div><small>Every post requires approval before Instagram publishing.</small></div></aside>
 <section className="main"><header><div><label>EDITORIAL AUTOMATION</label><h1>{tab}</h1><p>International news → natural Tamil → original visual → approval → Instagram.</p></div><button className="run" onClick={runTest} disabled={running}>{running?"Running…":"Run test"}</button></header>
 {tab==="Dashboard"&&<><div className="stats">{[["Active sources","01","Currently configured"],["Pending",String(pending.length),"Awaiting approval"],["Published",String(published.length),"Instagram posts"],["Errors","00","Needs attention"]].map(([a,b,c])=><div className="stat" key={a}><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div>
 <div className="panel"><div className="panelTitle"><div><h2>Automation pipeline</h2><p>Safe editorial workflow</p></div><em>APPROVAL MODE</em></div><div className="pipeline">{steps.map((s,i)=><div className="step" key={s}><div className="num">{String(i+1).padStart(2,"0")}</div><div><b>{s}</b><small>{i<2?"Ready":i===2?"AI processing":"Waiting"}</small></div><span className={i<2?"ready":i===2?"ai":"wait"}>{i<2?"●":i===2?"✦":"○"}</span></div>)}</div></div>
 <div className="panel"><div className="panelTitle"><div><h2>Latest test</h2><p>{result?result.ok?String(result.count||0)+" stories processed":result.error:"Click Run test to fetch and rewrite the latest stories."}</p></div></div></div></>}
 {tab==="Pending Posts"&&<div className="panel"><div className="panelTitle"><div><h2>Approval queue</h2><p>Review every story before it can reach Instagram.</p></div></div>{pending.length===0?<p>No pending stories yet. Run a test.</p>:pending.map(p=><article className="source" key={p.id} style={{display:"block",marginBottom:16}}><b>{p.editorial?.headline_tamil||p.title}</b><small style={{display:"block",marginTop:6}}>{p.source} · {p.status}</small><p>{p.editorial?.caption_tamil||p.summary}</p>{p.imageUrl&&<img src={p.imageUrl} alt="" style={{maxWidth:"100%",borderRadius:12,margin:"10px 0"}}/>}<div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button className="ghost" onClick={()=>moderate(p.id,"rejected")}>Reject</button>{p.status==="pending_approval"&&<button className="run" onClick={()=>generate(p)} disabled={imageBusy===p.id}>{imageBusy===p.id?"Creating…":"Approve + Create Graphic"}</button>}{p.status==="approved"&&<button className="run" onClick={()=>publish(p)}>Publish to Instagram</button>}</div></article>)}</div>}
 {tab==="Published"&&<div className="panel"><div className="panelTitle"><div><h2>Published</h2><p>Posts successfully sent to Instagram.</p></div></div>{published.length===0?<p>No published posts yet.</p>:published.map(p=><div className="source" key={p.id} style={{display:"block",marginBottom:10}}><b>{p.editorial?.headline_tamil||p.title}</b><small style={{display:"block"}}>{p.source} · published</small></div>)}</div>}
 {tab==="Sources"&&<div className="panel"><div className="panelTitle"><div><h2>News sources</h2><p>Only configured feeds are active.</p></div></div><div className="sourceGrid">{sources.map((s,i)=><div className="source" key={s}><span className="sourceDot"/><b>{s}</b><small>{i===4?"Configured":"Not configured yet"}</small></div>)}</div></div>}
 {tab==="Settings"&&<div className="panel"><div className="panelTitle"><div><h2>Admin access</h2><p>Stored only in this browser session.</p></div></div><input value={secret} onChange={e=>saveSecret(e.target.value)} placeholder="Enter ADMIN_SECRET" type="password" style={{width:"100%",padding:14,borderRadius:10,border:"1px solid #ddd"}}/><p style={{marginTop:12}}>Instagram publishing also requires the Meta credentials configured in Vercel.</p></div>}
 </section></main>;
}